name: penit_system_geosecure_quantum_demo
description: "Sistema Penitenciario Nacional de Guinea Ecuatorial - Versión Quantum 2025"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  fl_chart: ^0.66.0
  connectivity_plus: ^5.0.2
  image_picker: ^1.0.4
  flutter_local_notifications: ^16.3.0
  flutter_secure_storage: ^9.0.0
  http: ^1.1.0
  image: ^4.1.3
  path: ^1.8.3
  shared_preferences: ^2.2.2
  # PDF viewer for web
  syncfusion_flutter_pdfviewer: ^24.2.8
  encrypt: ^5.0.3
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/
    - assets/images/
    - assets/documents/ 